apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  type: NodePort
  selector:
    app: recipe
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
